### ISSUE TITLE
The causality on the height dimension ?

### ISSUE THREAD

**Issue by JesseYang** [L0SG/WaveFlow#3]
It seems that the [shift_1d](https://github.com/L0SG/WaveFlow/blob/f22d6cf6db0872756cb338f6e14127f529423cdc/model.py#L119) is called to guarantee the causality on the height dimension. But the receptive field of the following Wavenet2D module is greater than 3 (8 layers, each has kernel size of 3). Then how dose the shift_1d function which only shifts the tensor on height dimension by one unit guarantee the causality?

**Comment by yoyolicoris** [comment]
@JesseYang 
The Wavenet2D module is indeed causal to the affine transform input along the height dimension, I can't understand why receptive field has an impact on causality. If you mean the width dimension, there's no gaurantee of causality along width dimension in the original paper.

**Comment by L0SG** [comment]
The causality is guaranteed by implementing causal convolution along the height which [automatically matches the given filter size.](https://github.com/L0SG/WaveFlow/blob/23643a313570f5044d1bebcc718e09cdc5e33cfa/modules.py#L40)
